# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/golang-writing-web-applications
#
# Licensed under the BSD 3-Clause "New" or "Revised" License. See LICENSE file
# in the project root for full license information.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/brick#92
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

# Reminder: Sort this after every change
linters:
  enable:
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - govet

    # Deprecated linter, but still functional as of golangci-lint v1.39.0.
    # See https://github.com/atc0005/go-ci/issues/302 for more information.
    - maligned

    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
#
# Disable fieldalignment settings until the Go team offers more control over
# the types of checks provided by the fieldalignment linter or golangci-lint
# does so.
#
# See https://github.com/atc0005/go-ci/issues/302 for more information.
#

# disable:
# - maligned

# linters-settings:
# govet:
#   enable:
#     - fieldalignment
